language: java

sudo: required

jdk:
  - oraclejdk8

before_install:
  - git submodule update --quiet --init --recursive
  - sudo apt-get update && sudo apt-get install oracle-java8-installer

script:
  cd MAVGCL && ant all

